# Generated by Django 4.2.6 on 2023-10-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='createdTime',
        ),
    ]
